app:
  title: Wozcorp Backstage Platform
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  locations:
    - type: url
      target: https://raw.githubusercontent.com/felipecezaar/DevOpsGram-GitOps/feature/backstage/backstage/catalog-info.yaml

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'

integrations:
  github:
    - host: github.com
      # sem token para público
