apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Wozcorp Backstage Platform
      baseUrl: http://localhost:7007

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      cors:
        origin: ["http://localhost:3000", "http://localhost:7007"]
        methods: ["GET", "POST", "PUT", "DELETE"]
        credentials: true
      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      environment: development
      providers:
        guest:
          enabled: true
          allowAutoSignUp: true

    permission:
      enabled: true
      policies:
        - plugin: catalog
          policy: "entity.metadata.namespace == 'default'"

    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/felipecezaar/DevOpsGram-GitOps/feature/backstage/backstage/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Resource, Template]

    techdocs:
      builder: 'local'
      generator:
        runIn: 'local'

    integrations:
      github:
        - host: github.com