apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: LoadBalancer
  ports:
    - port: 7007
      targetPort: 7007
      protocol: TCP
      name: http
  selector:
    app: backstage
